educacioncuaz/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings 
from django.conf.urls.static import static
from usuarios import views

urlpatterns = [
    path('', views.Landing),
    path('admin/', admin.site.urls),
    path('educuaz/publication/', include('publication.urls', namespace='publication_app')),
    path('educuaz/', include('usuarios.urls', namespace='eduacionapp')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

publication/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

# from django.conf import settings 
# from django.conf.urls.static import static

app_name='publication_app'
urlpatterns = [
    path('<int:id>/', views.Publicacion, name='publication'),
    path('crearPublicacion/', views.crearPublicacion, name='crearPublicacion'),
    path('crearCarrusel/', views.crearCarrusel, name='crearCarrusel'),
    path('all/', views.allPublications, name='allPublications'),
    path('publicationAdmin/',views.publicationAdmin, name='publicationAdmin'),
    path('edicionPublication/<int:id>/',views.edicionPublication, name='edicionPublication'),
    path('eliminaPublicacion/<int:id>/', views.eliminaPublicacion, name='eliminaPublicacion'),
    path('carruselAdmin/',views.carruselAdmin, name='carruselAdmin'),
    path('edicionCarrusel/<int:id>/',views.edicionCarrusel, name='edicionCarrusel'),
    path('eliminaCarrusel/<int:id>/', views.eliminaCarrusel, name='eliminaCarrusel'),
    path('crearEscuela/', views.crearEscuela, name='crearEscuela'),
    path('escuelaAdmin/',views.escuelaAdmin, name='escuelaAdmin'),
    path('edicionEscuela/<int:id>/',views.edicionEscuela, name='edicionEscuela'),
    path('eliminaEscuela/<int:id>/', views.eliminaEscuela, name='eliminaEscuela'),
    path('schoolView/<int:id>/',views.schoolView, name='schoolView'),
    path('adminCenter/',views.adminCenter, name='adminCenter'),
    # nuevos campos
    path('crearObjetivo/', views.crearObjetivo, name='crearObjetivo'),
    path('crearMision/', views.crearMision, name='crearMision'),
    path('crearPlanDeTrabajo/', views.crearPlanDeTrabajo, name='crearPlanDeTrabajo'),
    # index
    path('indexObjetivo/',views.indexObjetivo, name='indexObjetivo'),
    path('indexMision/',views.indexMision, name='indexMision'),
    path('indexPlanDeTrabajo/',views.indexPlanDeTrabajo, name='indexPlanDeTrabajo'),
    # editar nuevos campos
    path('editObjetivo/<int:id>/',views.editObjetivo, name='editObjetivo'),
    path('editMision/<int:id>/',views.editMision, name='editMision'),
    path('editPlanDeTrabajo/<int:id>/',views.editPlanDeTrabajo, name='editPlanDeTrabajo'),
    #  eliminar
    path('eliminarObjetivo/<int:id>/', views.eliminarObjetivo, name='eliminarObjetivo'),
    path('eliminarMision/<int:id>/', views.eliminarMision, name='eliminarMision'),
    path('eliminarPlanDeTrabajo/<int:id>/', views.eliminarPlanDeTrabajo, name='eliminarPlanDeTrabajo'),
    # navbar
    path('navObjetivo/', views.navObjetivo, name='navObjetivo'),
    path('navMision/', views.navMision, name='navMision'),
    path('navPlanDeTrabajo/', views.navPlanDeTrabajo, name='navPlanDeTrabajo'),
    # Previsualizar 
    path('preObjetivo/<int:id>/', views.preObjetivo, name='preObjetivo'),
    path('preMision/<int:id>/', views.preMision, name='preMision'),
    path('prePlanDeTrabajo/<int:id>/', views.prePlanDeTrabajo, name='prePlanDeTrabajo'),
    # Reglamento'
    path('crearReglamento/', views.crearReglamento, name='crearReglamento'),
    path('indexReglamento/',views.indexReglamento, name='indexReglamento'),
    path('editReglamento/<int:id>/',views.editReglamento, name='editReglamento'),
    path('eliminarReglamento/<int:id>/', views.eliminarReglamento, name='eliminarReglamento'),
    path('navReglamento/', views.navReglamento, name='navReglamento'),
    path('preReglamento/<int:id>/', views.preReglamento, name='preReglamento'),



] 

# urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

usuarios/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from . import templates

app_name='eduacionapp'

#Aqui se determinan las urls a las que se puede acceder a la página
urlpatterns = [
    path('home/', views.Home, name='home'),
    path('landing/', views.Landing, name='landing'),
    path('avisos/', views.Avisos, name='avisos'),
    path('login/', views.Login.as_view(), name='login'),
    path('register/', views.Register.as_view(), name='register'),
    path('editar/<int:id>', views.editar_usuario, name='editar'),
    path('editar_permisos/<int:id>', views.editar_permisos, name='editar_permisos'),
    path('delete/<int:id>/', views.elimina_usuario, name='borrar'),
    path(r'logout/', auth_views.LogoutView.as_view(), name='logout'),
]

publication/views.py
from django.shortcuts import render, redirect
from .forms import MisionForm, PlanDeTrabajoForm, PublicationForm,CarruselForm, ReglamentoForm, SchoolForm, ObjetivoForm

# from publication import Publications
from publication.models import Publication, Carousel, Reglamento, School, Objetivo, Mision, PlanDeTrabajo
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import ListView
import os

def Publicacion(request, id):
    article = Publication.objects.get(id=id)
    all_article = Publication.objects.all().order_by('-published')
    all_article = all_article[0:6]
    context = {'article': article, 
                'all_article':all_article}

    return render(request, 'publicacion.html', context)

@login_required(login_url='eduacionapp:login')
def crearPublicacion(request):
    if request.method == "POST":
        form = PublicationForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('publication_app:publicationAdmin')
            
    else:
        form = PublicationForm()
    return render(request, 'crearPublicacion.html', {'form': form})

@login_required(login_url='eduacionapp:login')
def crearCarrusel(request):
    if request.method == "POST":
        form = CarruselForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('publication_app:carruselAdmin')
    else:
        form = CarruselForm()
    return render(request, 'crearCarrusel.html', {'form': form})


def allPublications(request):
    # all publications sort by desc
    all_publications = Publication.objects.all().order_by('-published')
    context = {
                'all_publications': all_publications,
    }
    return render(request, 'allPublications.html',context)

@staff_member_required(login_url='eduacionapp:login')
def publicationAdmin(request):
    # all publications sort by desc
    all_publications = Publication.objects.all()
    context = {
                'all_publications': all_publications,
    }
    return render(request, 'publicationAdmin.html',context)

@login_required(login_url='eduacionapp:login')
def edicionPublication(request, id):
    article =Publication.objects.get(id=id)
    form = PublicationForm(instance=article)
    if request.method == 'POST':
        form = PublicationForm(request.POST, request.FILES , instance=article)
        if form.is_valid():
            form.save()
            return redirect('publication_app:publicationAdmin')
    context = {'form': form}
    return render(request, 'editarPublicacion.html', context)


@login_required(login_url='eduacionapp:login')
def eliminaPublicacion(request, id):
    publication = Publication.objects.get(id=id)
    if request.method == "POST":
        publication.delete()
        return redirect('publication_app:publicationAdmin')

    context = {'publication': publication}
    return render(request, 'eliminarPublicacion.html', context)

@staff_member_required(login_url='eduacionapp:login')
def carruselAdmin(request):
    # all publications sort by desc
    all_carrusels = Carousel.objects.all()
    context = {
                'all_carrusels': all_carrusels,
    }
    return render(request, 'carruselAdmin.html',context)

@login_required(login_url='eduacionapp:login')
def edicionCarrusel(request, id):
    article =Carousel.objects.get(id=id)
    form = CarruselForm(instance=article)
    if request.method == 'POST':
        form = CarruselForm(request.POST, request.FILES , instance=article)
        if form.is_valid():
            form.save()
            return redirect('publication_app:carruselAdmin')
    context = {'form': form}
    return render(request, 'editarCarrusel.html', context)

@login_required(login_url='eduacionapp:login')
def eliminaCarrusel(request, id):
    carrusel = Carousel.objects.get(id=id)
    if request.method == "POST":
        carrusel.delete()
        return redirect('publication_app:carruselAdmin')

    context = {'carrusel': carrusel}
    return render(request, 'eliminarCarrusel.html', context)

@login_required(login_url='eduacionapp:login')
def crearEscuela(request):
    if request.method == "POST":
        form = SchoolForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            
            return redirect('publication_app:escuelaAdmin')

    else:
        form = SchoolForm()
    return render(request, 'crearEscuela.html', {'form': form})

@staff_member_required(login_url='eduacionapp:login')
def escuelaAdmin(request):
    # all publications sort by desc
    all_school = School.objects.all()
    context = {
                'all_school': all_school,
    }
    return render(request, 'escuelaAdmin.html',context)

@login_required(login_url='eduacionapp:login')
def edicionEscuela(request, id):
    article =School.objects.get(id=id)
    #print(article)
    form = SchoolForm(instance=article)
    #print(form)
    if request.method == 'POST':
        form = SchoolForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            return redirect('publication_app:escuelaAdmin')
    context = {'form': form}
    return render(request, 'editarEscuelas.html', context)

def schoolView(request, id):
    school = School.objects.get(id=id)
    
    # second section img rectangle speccific  1, 2, 3
    s_sec1 = Publication.objects.all().filter(Universidad=school.Universidad, section='1')
    s_sec1 = s_sec1[0:1]
    s_sec2 = Publication.objects.all().filter(Universidad=school.Universidad, section='2')
    s_sec2 = s_sec2[0:1]
    s_sec3 = Publication.objects.all().filter(Universidad=school.Universidad, section='3')
    s_sec3 = s_sec3[0:1]
    # third section img square
    t_sec = Publication.objects.all().filter( Universidad=school.Universidad, section='T')
    t_sec = t_sec[0:3]
    context = {'school': school,
                's_sec1': s_sec1,
                's_sec2': s_sec2,
                's_sec3': s_sec3,
                't_sec': t_sec
                }

    #print(context)
    # article = Publication.objects.all()
    # print(public)
    return render(request, 'schoolView.html', context)

@login_required(login_url='eduacionapp:login')
def eliminaEscuela(request, id):
    school = School.objects.get(id=id)
    if request.method == "POST":
        school.delete()
        return redirect('publication_app:escuelaAdmin')

    context = {'school': school}
    return render(request, 'eliminarEscuela.html', context)



@staff_member_required(login_url='eduacionapp:login')
def adminCenter(request):
    
    return render(request, 'adminCenter.html')
# crear cosas---------------------------------------------------------------
@login_required(login_url='eduacionapp:login')
def crearObjetivo(request):
    if request.method == "POST":
        form = ObjetivoForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            print(post)
            post.save()
            return redirect('publication_app:indexObjetivo')
    else:
        form = ObjetivoForm()
    return render(request, 'crearObjetivo.html', {'form': form})
    
@login_required(login_url='eduacionapp:login')
def crearMision(request):
    print(request.method)    
    if request.method == "POST":
        form = MisionForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('publication_app:indexMision')
            
    else:
        form = MisionForm()
    return render(request, 'crearMision.html', {'form': form})
    
@login_required(login_url='eduacionapp:login')
def crearPlanDeTrabajo(request):
    if request.method == "POST":
        form = PlanDeTrabajoForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('publication_app:indexPlanDeTrabajo')
            
    else:
        form = PlanDeTrabajoForm()
    return render(request, 'crearPlanDeTrabajo.html', {'form': form})

# vistas en las que mostramos los datos ----------------------------------------------------

@staff_member_required(login_url='eduacionapp:login')
def indexObjetivo(request):
    objetivos = Objetivo.objects.all()
    context = {
                'objetivos': objetivos,
    }
    return render(request, 'indexObjetivo.html',context)

@staff_member_required(login_url='eduacionapp:login')
def indexMision(request):
    misiones = Mision.objects.all()
    context = {
                'misiones': misiones,
    }
    return render(request, 'indexMision.html',context)

@staff_member_required(login_url='eduacionapp:login')
def indexPlanDeTrabajo(request):
    planesDeTrabajo = PlanDeTrabajo.objects.all()
    print(planesDeTrabajo)
    context = {
                'planesDeTrabajo': planesDeTrabajo,
    }
    return render(request, 'indexPlanDeTrabajo.html',context)
# edit to new 3 -----------------------------------------------------------------------------
@login_required(login_url='eduacionapp:login')
def editObjetivo(request, id):
    article =Objetivo.objects.get(id=id)
    form = ObjetivoForm(instance=article)
    if request.method == 'POST':
        form = ObjetivoForm(request.POST, request.FILES , instance=article)
        if form.is_valid():
            form.save()
            return redirect('publication_app:indexObjetivo')
    context = {'form': form}
    return render(request, 'crearObjetivo.html', context)

@login_required(login_url='eduacionapp:login')
def editMision(request, id):
    article =Mision.objects.get(id=id)
    form = MisionForm(instance=article)
    if request.method == 'POST':

publication/templates/escuelaAdmin.html
{% extends "base_us.html" %}
{% block title %}
Carreras

{% endblock %}
{% load static %}

{% block content %}
<br>
<br>
<br>
<!-- Nueva forma de data table -->
<div class="container-fluid p-4 my-3 border">
    <div class="card">
        <div class="card-header">
            <div class="enlinea">
                <h2 class="app-page-title"> Unidades académicas</h2>
                <div class="text-end">
                    <a type="button" class="btn btn-primary" href="{% url 'publication_app:adminCenter' %}"
                        class="btn btn-outline-primary">Centro de administración</a>
                    <a type="button" class="btn btn-success" href="{% url 'publication_app:crearEscuela' %}"
                        class="btn btn-outline-success">Crear unidad académica</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped  table-bordered" id="tblUsu" style="width:100%">
                    <thead class="thead-dark">
                        <th>Nombre de carrera</th>
                        <th>Unidad UnidadAcademica</th>
                        <th>Acciones</th>

                    </thead>
                    <tbody>
                        {% for item in all_school %}
                        <tr>
                            <td>{{item.nombreCarrera}}</td>
                            <td>{{item.UnidadAcademica}}</td>
                            <td>
                                <a type="button" class="btn btn-primary"
                                    href="{% url 'publication_app:schoolView' item.id %}"
                                    class="btn btn-outline-success">ver</a>
                                <a type="button" class="btn btn-success"
                                    href="{% url 'publication_app:edicionEscuela' item.id %}"
                                    class="btn btn-outline-primary ">Editar</a>
                                <a type="button" class="btn btn-danger"
                                    href="{% url 'publication_app:eliminaEscuela' item.id %}"
                                    class="btn btn-outline-danger">Eliminar</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>

</div>
{% endblock %}

publication/templates/indexReglamento.html
{% extends "base_us.html" %}
{% block title %}
Reglamentación del ACS
{% endblock %}
{% load static %}

{% block content %}
<br>
<br>
<br>
<!-- nueva forma de verlo en datatable -->
<div class="container-fluid p-4 my-3 border">
    <div class="card">
        <div class="card-header">
            <div class="enlinea">
                <h2 class="app-page-title">Reglamentación del ACS</h2>
                <div class="text-end">
                    <a type="button" class="btn btn-primary" href="{% url 'publication_app:adminCenter' %}" class="btn btn-outline-primary">Centro de administración</a>
                    <a type="button" class="btn btn-success" href="{% url 'publication_app:crearReglamento' %}" class="btn btn-outline-success">Crear Reglamento</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped  table-bordered" id="tblUsu" style="width:100%">
                    <thead class="thead-dark">
                        <th>Titulo</th>
                        <th>Autor</th>
                        <th>Contenido</th>
                        <th>Activo</th>
                        <th>Acciones</th>
                    </thead>
                    <tbody>
                        {% for item in regalamento %}
                        <tr>
                            <td>{{item.title}}</td>
                            <td>{{item.author}}</td>
                            <td>{{item.content1}}</td>
                            {% if item.Activo == 'S' %}
                            <td>Si</td>
                            {% else %}
                            <td>No</td>
                            {% endif %}
                            <td>
                                <a type="button" class="btn btn-primary" href = "{% url 'publication_app:preReglamento' item.id %}" class = "btn btn-outline-success">ver</a>
                                <a type="button" class="btn btn-success" href = "{% url 'publication_app:editReglamento' item.id %}" class = "btn btn-outline-primary">Editar</a>
                                <a type="button" class="btn btn-danger" href = "{% url 'publication_app:eliminarReglamento' item.id %}" class = "btn btn-outline-danger" >Eliminar</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            

        </div>
    </div>

</div>
{% endblock %}

publication/templates/previaVistasNav.html
{% extends "base_us.html" %}
{% block title %}
{{article.title}}
{% endblock %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <article>
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{article.title}}</h1>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">Publicado el {{article.published}} por {{article.author}}
                    </div>
                </header>
                <figure class="mb-4">
                    {% if article.pic %}
                    <img class="card-img-top border-primary" src="{{article.pic.url}}" width="900"
                        height="400">
                    {% else %}
                    <img class="img-fluid rounded" src=" https://dummyimage.com/900x400/ced4da/6c757d.jpg">
                    {% endif %}
                </figure>
                <section class="mb-5">
                    <p class="fs-5 mb-4">{{article.content1}}</p>
                </section>
                <section class="mb-5">
                    {% if article.file1 %}
                    <hr>
                    <a class="fs-5 mb-4" href="{{article.file1.url}}"
                        target="_blank">{{article.file1}}</a>
                    {% endif %}
                </section>



        </div><!-- /.blog-post -->
        </article>
        <div class="col-lg-4">
            <div class="card mb-4">
                <div class="card-header">Atajos</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                <li><a href="{% url 'eduacionapp:landing' %}">Inicio</a></li>
                                <li><a href="{% url 'publication_app:allPublications' %}">Publicaciones</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card mb-4">
                <div class="card-header">Descripción</div>
                <div class="card-body">{{article.description}}</div>
            </div>
            <div class="card mb-4">
                <div class="card-header">Últimas publicaciones</div>
                <div class="card-body">
                    <div>
                        <ul class="list-unstyled mb-0">
                            {% for article in all_article %}
                            <li><a href="{% url 'publication_app:publication' article.id %}">{{article.title}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.row -->
    <br>
    <br>
    <br>
    {% endblock %}

publication/templates/publicacion.html
{% extends "base_us.html" %}
{% block title %}
{{article.title}}
{% endblock %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <article>
                <div class="card">


                    <div class="card-header">
                        <!-- Post title-->
                        <h1 class="fw-bolder mb-1">{{article.title}}</h1>
                        <!-- Post meta content-->
                    </div>
                    <div class="card-body">

                        <div class="text-muted fst-italic mb-2">Publicado el {{article.published}} por {{article.author}}</div>
                        <br>
                        <div class="d-flex justify-content-center">
                            <figure class="mb-4">
                                {% if article.publication_pic %}
                                <img class="card-img-top border-primary" src="{{article.publication_pic.url}}" width="600" height="400">
                                {% else %}
                                <img class="img-fluid rounded" src=" https://dummyimage.com/600x400/ced4da/6c757d.jpg">
                                {% endif %}
                            </figure>
                        </div>
                        <br>
                        
                        <section class="mb-5">
                            <p class="fs-5 mb-4">{{article.content1}}</p>
                            {% if article.content2 %}
                            <hr>
                            <p class="fs-5 mb-4">{{article.content2}}</p>
                            {% endif %}
                            {% if article.content2 %}
                            <hr>
                            <p class="fs-5 mb-4">{{article.content3}}</p>
                            {% endif %}
                        </section>
                        <section class="mb-5">
                            {% if article.file1 or article.file2 or article.file3 %}
                            <hr>
                            <p>Archivos adjuntos</p>
                            {% if article.file1 %}
                            <a class="fs-5 mb-4" href="{{article.file1.url}}"
                                target="_blank">{{article.file1}}</a>
                            {% endif %}
                            {% if article.file2 %}
                            <a class="fs-5 mb-4" href="{{article.file2.url}}"
                                target="_blank">{{article.file2}}</a>
                            {% endif %}
                            {% if article.file3 %}
                            <a class="fs-5 mb-4" href="{{article.file3.url}}"
                                target="_blank">{{article.file3}}</a>
                            {% endif %}
                            {% endif %}
        
                        </section>
                        
                    </div>

                </div>



            </div><!-- /.blog-post -->
        </article>
        <div class="col-lg-4">
            <div class="card mb-4">
                <div class="card-header">Atajos</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                <li><a href="{% url 'eduacionapp:landing' %}">Inicio</a></li>
                                <li><a href="{% url 'publication_app:allPublications' %}">Publicaciones</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card mb-4">
                <div class="card-header">Descripción</div>
                <div class="card-body">{{article.description}}</div>
            </div>
            <div class="card mb-4">
                <div class="card-header">Últimas publicaciones</div>
                <div class="card-body">
                    <div>
                        <ul class="list-unstyled mb-0">
                            {% for article in all_article %}
                            <li><a href="{% url 'publication_app:publication' article.id %}">{{article.title}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.row -->
    <br>
    <br>
    <br>
    {% endblock %}

publication/templates/vistasNav.html
{% extends "base_us.html" %}
{% block title %}
{{article.title}}
{% endblock %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <article>

            {% for article in articleNav %}
                <div class="card">
                    <div class="card-header">
                        <!-- Post title-->
                        <h1 class="fw-bolder mb-1">{{article.title}}</h1>
                        <!-- Post meta content-->
                    </div>
                    <div class="card-body">
                        <div class="text-muted fst-italic mb-2">Publicado el {{article.published}} por {{article.author}}</div>
                        <br>
                        <div class="d-flex justify-content-center">
                            <figure class="mb-4">
                                {% if article.pic %}
                                <img class="card-img-top border-primary" src="{{article.pic.url}}" width="600" height="400">
                                {% else %}
                                <img class="img-fluid rounded" src=" https://dummyimage.com/600x400/ced4da/6c757d.jpg">
                                {% endif %}
                            </figure>
                        </div>
                        <br>
                        <section class="mb-5">
                            <p class="fs-5 mb-4">{{article.content1}}</p>
                        </section>
                        <section class="mb-5">
                            {% if article.file1 %}
                            <hr>
                            <a class="fs-5 mb-4" href="{{article.file1.url}}" target="_blank">{{article.file1}}</a>
                            {% endif %}
                        </section>
                    </div>
                </div>
                <br>
            {% endfor %}


            </article>
        </div><!-- /.blog-post -->
        <div class="col-lg-4">
            <div class="card mb-4">
                <div class="card-header">Atajos</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                <li><a href="{% url 'eduacionapp:landing' %}">Inicio</a></li>
                                <li><a href="{% url 'publication_app:allPublications' %}">Publicaciones</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card mb-4">
                <div class="card-header">Últimas publicaciones</div>
                <div class="card-body">
                    <div>
                        <ul class="list-unstyled mb-0">
                            {% for article in all_article %}
                            <li><a href="{% url 'publication_app:publication' article.id %}">{{article.title}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.row -->
    <br>
    <br>
    <br>
    {% endblock %}