educacioncuaz/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings 
from django.conf.urls.static import static
from usuarios import views

urlpatterns = [
    path('', views.Landing),
    path('admin/', admin.site.urls),
    path('educuaz/publication/', include('publication.urls', namespace='publication_app')),
    path('educuaz/', include('usuarios.urls', namespace='eduacionapp')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

publication/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

# from django.conf import settings 
# from django.conf.urls.static import static

app_name='publication_app'
urlpatterns = [
    path('<int:id>/', views.Publicacion, name='publication'),
    path('crearPublicacion/', views.crearPublicacion, name='crearPublicacion'),
    path('crearCarrusel/', views.crearCarrusel, name='crearCarrusel'),
    path('all/', views.allPublications, name='allPublications'),
    path('publicationAdmin/',views.publicationAdmin, name='publicationAdmin'),
    path('edicionPublication/<int:id>/',views.edicionPublication, name='edicionPublication'),
    path('eliminaPublicacion/<int:id>/', views.eliminaPublicacion, name='eliminaPublicacion'),
    path('carruselAdmin/',views.carruselAdmin, name='carruselAdmin'),
    path('edicionCarrusel/<int:id>/',views.edicionCarrusel, name='edicionCarrusel'),
    path('eliminaCarrusel/<int:id>/', views.eliminaCarrusel, name='eliminaCarrusel'),
    path('crearEscuela/', views.crearEscuela, name='crearEscuela'),
    path('escuelaAdmin/',views.escuelaAdmin, name='escuelaAdmin'),
    path('edicionEscuela/<int:id>/',views.edicionEscuela, name='edicionEscuela'),
    path('eliminaEscuela/<int:id>/', views.eliminaEscuela, name='eliminaEscuela'),
    path('schoolView/<int:id>/',views.schoolView, name='schoolView'),
    path('adminCenter/',views.adminCenter, name='adminCenter'),
    # nuevos campos
    path('crearObjetivo/', views.crearObjetivo, name='crearObjetivo'),
    path('crearMision/', views.crearMision, name='crearMision'),
    path('crearPlanDeTrabajo/', views.crearPlanDeTrabajo, name='crearPlanDeTrabajo'),
    # index
    path('indexObjetivo/',views.indexObjetivo, name='indexObjetivo'),
    path('indexMision/',views.indexMision, name='indexMision'),
    path('indexPlanDeTrabajo/',views.indexPlanDeTrabajo, name='indexPlanDeTrabajo'),
    # editar nuevos campos
    path('editObjetivo/<int:id>/',views.editObjetivo, name='editObjetivo'),
    path('editMision/<int:id>/',views.editMision, name='editMision'),
    path('editPlanDeTrabajo/<int:id>/',views.editPlanDeTrabajo, name='editPlanDeTrabajo'),
    #  eliminar
    path('eliminarObjetivo/<int:id>/', views.eliminarObjetivo, name='eliminarObjetivo'),
    path('eliminarMision/<int:id>/', views.eliminarMision, name='eliminarMision'),
    path('eliminarPlanDeTrabajo/<int:id>/', views.eliminarPlanDeTrabajo, name='eliminarPlanDeTrabajo'),
    # navbar
    path('navObjetivo/', views.navObjetivo, name='navObjetivo'),
    path('navMision/', views.navMision, name='navMision'),
    path('navPlanDeTrabajo/', views.navPlanDeTrabajo, name='navPlanDeTrabajo'),
    # Previsualizar 
    path('preObjetivo/<int:id>/', views.preObjetivo, name='preObjetivo'),
    path('preMision/<int:id>/', views.preMision, name='preMision'),
    path('prePlanDeTrabajo/<int:id>/', views.prePlanDeTrabajo, name='prePlanDeTrabajo'),
    # Reglamento'
    path('crearReglamento/', views.crearReglamento, name='crearReglamento'),
    path('indexReglamento/',views.indexReglamento, name='indexReglamento'),
    path('editReglamento/<int:id>/',views.editReglamento, name='editReglamento'),
    path('eliminarReglamento/<int:id>/', views.eliminarReglamento, name='eliminarReglamento'),
    path('navReglamento/', views.navReglamento, name='navReglamento'),
    path('preReglamento/<int:id>/', views.preReglamento, name='preReglamento'),



] 

# urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

usuarios/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from . import templates

app_name='eduacionapp'

#Aqui se determinan las urls a las que se puede acceder a la página
urlpatterns = [
    path('home/', views.Home, name='home'),
    path('landing/', views.Landing, name='landing'),
    path('avisos/', views.Avisos, name='avisos'),
    path('login/', views.Login.as_view(), name='login'),
    path('register/', views.Register.as_view(), name='register'),
    path('editar/<int:id>', views.editar_usuario, name='editar'),
    path('editar_permisos/<int:id>', views.editar_permisos, name='editar_permisos'),
    path('delete/<int:id>/', views.elimina_usuario, name='borrar'),
    path(r'logout/', auth_views.LogoutView.as_view(), name='logout'),
]

usuarios/models.py
from django.contrib.auth.models import User
from django.db import models

usuarios/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms


class UsuarioForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].label = 'Introduce tu contraseña'
        self.fields['password2'].label = 'Introduce tu contraseña nuevamente'
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''
        self.fields['username'].help_text = ''

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido'}),
            'username': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Matrícula'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'}),
        }

usuarios/views.py
from .forms import UsuarioForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User

from .decorators import unauthenticated_user
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.shortcuts import render, redirect
#importa los grupos que tienen diferentes permisos
from django.contrib.auth.models import Group
#Desde la otra aplicación
from publication.models import Carousel, Publication, School
from django.contrib.auth.decorators import login_required


#Esta clase se utiliza para realizar el registro de un nuevo usuario en la plataforma web
#@method_decorator(unauthenticated_user, name='dispatch')
class Register(CreateView):
    model = User
    template_name = "register.html"
    form_class = UsuarioForm

    success_url = reverse_lazy('eduacionapp:login')

#Esta clase se utiliza para iniciar sesion dentro de la plataforma web
@method_decorator(unauthenticated_user, name='dispatch')
class Login(LoginView):
    template_name = 'login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('eduacionapp:adminCenter')

#Esta clase es para organizar el contenido base de la plataforma web
@login_required(login_url='eduacionapp:login')
def Home(request):
    usuarios = User.objects.all()
    context = {'usuarios': usuarios}
    return render(request, 'home.html', context)


def Landing(request):
    # first section img rounded
    f_sec = School.objects.all()
    # deliminta el numero de publicaciones
    f_sec = f_sec[0:6]
    # second section img rectangle speccific  1, 2, 3
    s_sec1 = Publication.objects.all().filter(Universidad='n', section='1')
    s_sec1 = s_sec1[0:1]
    s_sec2 = Publication.objects.all().filter(Universidad='n', section='2')
    s_sec2 = s_sec2[0:1]
    s_sec3 = Publication.objects.all().filter(Universidad='n', section='3')
    s_sec3 = s_sec3[0:1]
    # third section img square
    t_sec = Publication.objects.all().filter(Universidad='n', section='T')
    t_sec = t_sec[0:3]

    # carousel section 
    c_sec_1 = Carousel.objects.all().filter(ordenPublication='1')[0:1]
    c_sec_2 = Carousel.objects.all().filter(ordenPublication='2')[0:1]
    c_sec_3 = Carousel.objects.all().filter(ordenPublication='3')[0:1]

    context = {
                'f_sec': f_sec,
                's_sec1': s_sec1,
                's_sec2': s_sec2,
                's_sec3': s_sec3,
                't_sec': t_sec,
                'c_sec_1': c_sec_1,
                'c_sec_2': c_sec_2,
                'c_sec_3': c_sec_3,
    }

    return render(request, 'landing.html',context)

def Avisos(request):
    return render(request, 'avisos.html')

class ListaUsuario(ListView):
    model = User

@login_required(login_url='eduacionapp:login')
def editar_usuario(request, id):
    usuario = User.objects.get(id=id)
    form = UsuarioForm(instance=usuario)
    if request.method == 'POST':
        form = UsuarioForm(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            return redirect('eduacionapp:home')
    context = {'form': form}
    return render(request, 'editar_usuario.html', context)

# Elimina un usario
@login_required(login_url='eduacionapp:login')
def elimina_usuario(request, id):
    usua = User.objects.get(id=id)
    if request.method == "POST":
        usua.delete()
        return redirect('eduacionapp:home')

    context = {'usua': usua}
    return render(request, 'delete.html', context)

#Modifica los permisos de un usuario
@login_required(login_url='eduacionapp:login')
def editar_permisos(request, id):
    usua =User.objects.get(id=id)
    group_al = Group.objects.get(name='alumno')
    group_pro = Group.objects.get(name='profesor')


    # seleccionar el tipo de permiso a mano
    if request.method == "POST":
        #identidica el permiso
        #Eres un estudiante
        if '_estudiante' in request.POST:
            print(usua.groups.all()[0])
            #quitamos los grupos
            usua.groups.clear()
            #le da permiso de estudiante
            usua.groups.add(group_al)


        #Entonces eres un profesor
        else:
            # Le da permiso de profesor
            usua.groups.clear()
            usua.groups.add(group_pro)
        #usua.delete()
        return redirect('eduacionapp:home')
    #Se le entrega los datos para mostrarlos
    context = {'usua': usua}
    return render(request, 'editar_permisos.html', context)

usuarios/templates/avisos.html
{% extends "base_us.html" %}
{% block title %}
landing
{% endblock %}
{% load static %}
{% block content %}
    <h4>amigouuuu</h4>
{% endblock %}

usuarios/templates/base_bootstrap.html
<!DOCTYPE html>
<html class="container1">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}{% endblock %}</title>
        <!-- tema y boostrap 4 online -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        
        <!-- fin tema y boostrap 4 -->
        {% block head %} {% endblock %}
        <!-- Data table online -->
            <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.11.3/datatables.min.css" />
            <link rel="stylesheet" rel="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
            <link rel="stylesheet" rel="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap4.min.css">
        <!-- Fin Data table online -->
    </head>
        <!-- Codigo java script nativo que usa boostrap -->
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
                integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
                crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
                integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
                crossorigin="anonymous"></script>
        <!-- fin Codigo java script nativo que usa boostrap  -->

    <body>
        <header>
            {% block navbar %} {% endblock %}
        </header>

            {% block content %}{% endblock %}
        
        <!-- pie de pagina  -->
            <footer class="card-footer text-center text-white  fixed-bottom" style="background-color: #222">
                <p class="small"><a href="{% url 'eduacionapp:login' %}">&copy; Desarrollado por el Laboratorio Universitario de Innovación, bajo la Licencia General Public License 3.0</a></p>
            </footer>
        <!-- fin de pie de pagina  -->
        <!-- dibujado de datatable -->
        <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.3/datatables.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $('#tblUsu').DataTable();
            });
        </script>
        <!-- fin dibujado de datatable -->
    </body>
</html>

usuarios/templates/base_us.html
{% extends "base_bootstrap.html" %}
{% block navbar %}

{% load static %}

<style>
  .navbar-brand {
    transform: translateX(-50%);
    left: 50%;
    position: absolute;
  }

  .navbar-custom {
    height: 100px;
  }

  @media (max-width: 770px) {
    .cosoNav {
      display: none !important;
    }
  }

  .enlinea {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  body{
    background-color: #ededed;
  }
  .dorado{
    color: #F1C40F;
  }

  .borde{
    -webkit-filter: drop-shadow(1px 1px 0 white)
                drop-shadow(-1px 1px 0 white)
                drop-shadow(1px -1px 0 white)
                drop-shadow(-1px -1px 0 white);

filter: drop-shadow(1px 1px 0 white)
        drop-shadow(-1px 1px 0 white)
        drop-shadow(1px -1px 0 white)
        drop-shadow(-1px -1px 0 white);
  }

</style>

  <nav class="navbar navbar-expand-md navbar-dark fixed-top " style="background-color: #001f46">
    

    <div class="collapse navbar-collapse d-md-flex justify-content-between" id="navbarCollapse">
      
      <ul class="navbar-nav mr-auto p-4">
        <li class="nav-item">
          <a class="nav-link h5 dorado" href="{% url 'publication_app:navMision' %}">Misión</a>
        </li>
        <li class="nav-item">
          <a class="nav-link h5 dorado" href="{% url 'publication_app:navObjetivo' %}">Objetivo</a>
        </li>
        <li class="nav-item">
          <a class="nav-link h5 dorado" href="{% url 'publication_app:navPlanDeTrabajo' %}">Plan de trabajo</a>
        </li>
        <li class="nav-item">
          <a class="nav-link h5 dorado" href="{% url 'publication_app:navReglamento' %}">Reglamentación del ACS</a>
        </li>
      </ul>
      <div class="d-none d-md-block  ">
        <ul class="navbar-nav mr-auto ">
          <li class="nav-item">
            <a href="{% url 'eduacionapp:landing'%}"><img src="{% static 'images/logo_uaz.png'%}" class="borde" alt="Generic placeholder image" width="90" height="90" class="rounded"></a>
          </li>
          <li>
            <a href="{% url 'eduacionapp:landing'%}"><img src="{% static 'images/medicina.png'%}" class="borde" alt="Generic placeholder image" width="90" height="90" class="rounded"></a>
          </li>
          <li>
            <a href="{% url 'eduacionapp:landing'%}"><img src="{% static 'images/enfer.png'%}"  class="borde" alt="Generic placeholder image" width="90" height="90" class="rounded"></a>
          </li>
          <li>
            <a href="{% url 'eduacionapp:landing'%}"><img src="{% static 'images/odonto.png'%}" class="borde" alt="Generic placeholder image" width="90" height="90" class="rounded"></a>
          </li>
          <li>
            <a href="{% url 'eduacionapp:landing'%}"><img src="{% static 'images/cq.png'%}" class="borde" alt="Generic placeholder image" width="90" height="90" class="rounded"></a>
          </li>
          <li>
            <a href="{% url 'eduacionapp:landing'%}"><img src="{% static 'images/acs.png'%}" class="borde" alt="Generic placeholder image" width="90" height="90" class="rounded"></a>
          </li>
        </ul>
      </div>


      <ul class="navbar-nav mr-auto p-4">
        {% if user.username == "admin" %}
        <li class="nav-item">
          <a class="nav-link h5 dorado" href="{% url 'publication_app:adminCenter' %} ">Centro de administración</a>
        </li>
        <li class="nav-item">
          <a class="nav-link h5 dorado" href="{% url 'eduacionapp:logout' %}?next={% url 'eduacionapp:login' %}">Cerrar Sesión</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link h5 dorado" href="{% url 'eduacionapp:landing'%}">Portal Académico del Área de Ciencias de la Salud</a>
        </li>
        {% endif %} 
      </ul>
    </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-toggler dorado" href="{% url 'eduacionapp:landing'%}" style=" text-decoration:none;"><p style="font-size: 12px;">Portal Académico del Área de Ciencias de la Salud</p></a>
  </nav>


{% endblock %}

usuarios/templates/delete.html
{% extends "base_us.html" %}

{% block title %}
Borrar usuario
{% endblock %}

{% block content %}
<h1>Borrar usuario {{ order.id }}</h1>
<div class="app-card app-card-orders-table shadow-sm mb-5">
  <hr>
  <br>
  <div class="container card mb-3" style="width: 30rem;">
    <div class="sign-form ">
      <table class="table">
        <thead>
          <th>Matricula</th>
          <th>Nombre(s)</th>
          <th>Acciones</th>
        </thead>
        <tbody>
          <tr>
            <td>{{usua.username}}</td>
            <td>{{usua.first_name}}</td>
            <td>{{usua.last_name}}</td>
          </tr>
        </tbody>
      </table>
      <form method="post" class="order-form">
        <p><input type="submit" value="Confirm"></p>
        {% csrf_token %}
      </form>
    </div>
  </div>
</div>
{% endblock %}

usuarios/templates/editar_permisos.html
{% extends "base_us.html" %}
{% block title %}
Registrar Nuevo Usuario
{% endblock %}

{% block content %}
<br>
<br>
<br>
<div class="app-card app-card-orders-table shadow-sm mb-5">
    <table class="table">
        <thead>
            <th>Matricula</th>
            <th>Nombre</th>
            <th>permiso</th>
            <th>Selecciona el permiso</th>
            <th></th>
        </thead>
        <tbody>
            <tr>
                {% if usua.username != "admin" %}
                <td>{{usua.username}}</td>
                <td>{{usua.first_name}} {{usua.last_name}}</td>
                <td>{{usua.groups.last}}</td>
                <td>
                    <form method="post" class="order-form">
                        <input class="btn btn-success" type="submit" value="alumno" name="_estudiante"
                            href="{% url 'eduacionapp:home' %}">
                        <input class="btn btn-info" type="submit" value="Profesor" href="{% url 'eduacionapp:home' %}">
                        {% csrf_token %}
                    </form>
                </td>
                <td><a class="btn  btn-danger" href="{% url 'eduacionapp:home' %}" role="button">Cancelar</a></td>
            </tr>

            {% endif %}
        </tbody>

    </table>

</div>

{% endblock %}

usuarios/templates/home.html
{% extends "base_us.html" %}

{% block title %}
Login
{% endblock %}

{% load static %}

{% block content %}
<br>
<br>
<br>
<br>
<!-- Cosas que muestra para el administrador  -->
{% if request.user.is_staff %}
<div class="container-fluid p-4 my-3 border">
  <h2 class="app-page-title"> Lista de usuarios</h2>
  <div class="table-responsive">
    <table class="table table-striped  table-bordered" id="tblUsu" style="width:100%">
      <thead class="thead-dark">
        <th>Matricula</th>
        <th>Nombre(s)</th>
        <th>Apellido(s)</th>
        <th>Correo</th>
        <th>Rol</th>
        <th>Acciones</th>

      </thead>
      <tbody>
        {% for item in usuarios %}
        {% if item.username != "admin" %}
        <tr>

          <td>{{item.username}}</td>
          <td>{{item.first_name}}</td>
          <td>{{item.last_name}}</td>
          <td>{{item.email}}</td>

          <td>
            {% if item.groups.all.0.name == "alumno" %}
            <button type="button" class="btn btn-outline-success">{{item.groups.last}}</button>

            {% else %}
            <button type="button" class="btn btn-outline-info">{{item.groups.last}}</button>

            {% endif %}

          </td>
          <td>
            <a class="btn btn-primary" href="{% url 'eduacionapp:editar' item.id %}" class="btn btn-outline-primary btn-sm">Modificar Informacion</a>
            <a class="btn btn-success" href="{% url 'eduacionapp:editar_permisos' item.id %}" class="btn btn-outline-primary btn-sm">Modificar Permisos</a>
            <a class="btn btn-danger" href="{% url 'eduacionapp:borrar' item.id %}" class="btn btn-outline-danger btn-sm">Eliminar</a>
          </td>
        </tr>


        {% endif %}

        {% endfor %}
      </tbody>
    </table>
  </div>
  <a type="button" class="btn btn-primary" href="{% url 'publication_app:adminCenter' %}" class="btn btn-outline-primary">Centro de administración</a>
    <a type="button" class="btn btn-success" href="{% url 'eduacionapp:register' %}" class="btn btn-outline-success">Crear Usuario</a>
</div>

{% else %}
{% if user.is_authenticated %}
<div class="card-deck card mb-3">
  <!-- Cosas que muestra para el alumno  -->
  {% if request.user.groups.all.0.name == "alumno" %}
  <div class="card" style="max-width: 18rem;"> {# el stile define que tan ancha puede ser la tarjerta, 286x180 la
    imagen#}
    <img class="card-img-top" src="{% static 'images/bienvenido.png' %} " alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Eventos</h5>
      <p class="card-text">Bienvenido,en este apartado se mostrarán los acontecimientos más recientes.</p>
      <a class="d-flex card-text justify-content-center mt-3 login_container"
        href="https://www.facebook.com/%C3%81rea-de-Ciencias-de-la-Salud-110339776102678/?ref=page_internalws">Entrar</a>
    </div>
  </div>
  <!-- Cosas que muestra para el profesor  -->
  {% elif request.user.groups.all.0.name == "profesor"%}
  <div class="card" style="max-width: 18rem;">
    <img class="card-img-top" src="{% static 'images/bienvenido.png' %} " alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Eventos</h5>
      <p class="card-text">Bienvenido,en este apartado se mostrarán los acontecimientos más recientes.</p>
      <a class="d-flex card-text justify-content-center mt-3 login_container"
        href="https://www.facebook.com/%C3%81rea-de-Ciencias-de-la-Salud-110339776102678/?ref=page_internalws">Entrar</a>
    </div>
  </div>
  {% endif %}
  <div class="card" style="max-width: 18rem;">
    <img class="card-img-top" src="{% static 'images/moodle.png' %} " alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Moodle</h5>
      <p class="card-text">Plataforma de aprendizaje diseñada para educacdores y estudiantes.</p>
      <a class="d-flex card-text justify-content-center mt-3 login_container" href="#">Entrar</a>
    </div>
  </div>
  <div class="card" style="max-width: 18rem;">
    <img class="card-img-top" src="{% static 'images/chamilo.png' %} " alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Chamilo</h5>
      <p class="card-text">Plataforma de aprendizaje diseñada para educacdores y estudiantes.</p>
      <a class="d-flex card-text justify-content-center mt-3 login_container" href="#">Entrar</a>
    </div>
  </div>

  <div class="card" style="max-width: 18rem;">
    <img class="card-img-top" src="{% static 'images/videollamadas.png' %} " alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Video llamadas</h5>
      <p class="card-text">Sala de conferencias, en las que pudes unirte u organizar reuniones.</p>
      <a class="d-flex card-text justify-content-center mt-3 login_container" href="#">Entrar</a>
    </div>
  </div>

  <div class="card" style="max-width: 18rem;">
    <img class="card-img-top" src="{% static 'images/gestiondocumental.png' %} " alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Gestion documental</h5>
      <p class="card-text">Plataforma en la que puedes realizar tramites y guardar documentos.</p>
      <a class="d-flex card-text justify-content-center mt-3 login_container" href="#">Entrar</a>
    </div>
  </div>
</div>
{% endif %}
{% endif %}

{% endblock %}

usuarios/templates/login.html
{% extends "base_us.html" %}
{% block title %}
Login
{% endblock %}
{% load static %}
<style>
    .card {
        margin: 0 auto;
        /* Added */
        float: none;
        /* Added */
        margin-bottom: 10px;
        /* Added */
    }
</style>
{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container d-flex justify-content-center">
    <div class="card ">
        <div class="card-body " style="width: 18rem;">
            <div>
                <img class="card-img-top" src="{% static 'images/uaz.jpg' %} " alt="Card image cap">
            </div>
            <br>
            <div>
                <form method="post">
                    {% csrf_token %}
                    <div class="input-group mb-3 justify-content-center">
                        <div>
                            <p class="card-text">Usuario:</p>
                            {{ form.username }}
                        </div>
                    </div>
                    <div class="input-group mb-3 justify-content-center">
                        <div>
                            <p class="card-text">Contraseña: </p>
                            {{ form.password }}
                        </div>
                    </div>
                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="btn btn-primary " type="submit" value="Acceder" href="{% url 'eduacionapp:home' %}">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}